/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import java.awt.Font;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import util.Configuracion;

/**
 *
 * @author jcsp0003
 */
public class FormatoFrame extends javax.swing.JDialog {

    private Font font;
    private final InterfazFrame inter;
    private final Configuracion config;

    /**
     * Creates new form FormatoFrame
     *
     * @param parent Frame intermaz padre
     * @param modal Booleano que indica si en necesario cerrar esa interfaz para modificar la padre
     * @param f Fuente del texto
     * @param in Frame intermaz padre
     * @param conf Configuracion del predictor
     */
    public FormatoFrame(java.awt.Frame parent, boolean modal, Font f, InterfazFrame in, Configuracion conf) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.config = conf;
        setIdiomaInterfaz();

        this.inter = in;
        this.jTextArea1.setLineWrap(true);
        this.font = f;

        jTextField1.setText(this.font.getName());
        switch (this.font.getStyle()) {
            case 0:
                jTextField2.setText("Normal");
                break;
            case 1:
                jTextField2.setText("Negrita");
                break;
            case 2:
                jTextField2.setText("Cursiva");
                break;
        }
        jTextField4.setText(Integer.toString(this.font.getSize()));

        jList1.addListSelectionListener(new ListSelectionListenerFuente(this));
        jList2.addListSelectionListener(new ListSelectionListenerEstilo(this));
        jList4.addListSelectionListener(new ListSelectionListenerTam(this));
        jTextArea1.setFont(font);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Fuente:");

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {"Aharoni", "Algerian", "Andalus", "Arial", "Arial Black", "Arial Narrow", "Batang", "BatangChe", "Bauhaus 93", "Bell MT", "Book Antiqua", "Britannic Bold", "Broadway", "Browallia New", "BrowalliaUPC", "Calibri", "Calibri Light", "Californian FB", "Cambria", "Cambria Math", "Candara", "Centaur", "Century", "Century Gothic", "Chiller", "Colonna MT", "Comic Sans MS", "Consolas", "Constantia", "Cooper Black", "Corbel", "Cordia New", "CordiaUPC", "Courier New", "DaunPenh", "David", "DFKai-SB", "Dialog", "DialogInput", "DilleniaUPC", "DokChampa", "Dotum", "DotumChe", "Ebrima", "Gabriola", "Garamond", "Gautami", "Georgia", "Gisha", "Gulim", "GulimChe", "Gungsuh", "GungsuhChe", "Harrington", "Impact", "Informal Roman", "IrisUPC",
                "Iskoola Pota", "JasmineUPC", "Jokerman", "Juice ITC", "KaiTi", "Kalinga", "Kartika", "Khmer UI", "KodchiangUPC", "Kokila", "Kristen ITC", "Kunstler Script", "Lao UI", "Latha", "Leelawadee", "Levenim MT", "LilyUPC", "Magneto", "Malgun Gothic", "Mangal", "Marlett", "MingLiU", "MingLiU-ExtB", "Miriam Fixed", "Mistral", "Monospaced", "MV Boli", "Narkisim", "NSimSun", "Nyala", "Onyx", "Palatino Linotype", "Parchment", "Playbill", "PMingLiU", "Poor Richard", "Raavi", "Ravie", "Rod", "Sakkal Majalla", "SansSerif", "Segoe Print", "Segoe Script", "Segoe UI", "Segoe UI Light", "Tahoma", "Times New Roman", "Traditional Arabic"};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Fuente:");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {"Aharoni", "Algerian", "Andalus", "Arial", "Arial Black", "Arial Narrow", "Batang", "BatangChe", "Bauhaus 93", "Bell MT", "Book Antiqua", "Britannic Bold", "Broadway", "Browallia New", "BrowalliaUPC", "Calibri", "Calibri Light", "Californian FB", "Cambria", "Cambria Math", "Candara", "Centaur", "Century", "Century Gothic", "Chiller", "Colonna MT", "Comic Sans MS", "Consolas", "Constantia", "Cooper Black", "Corbel", "Cordia New", "CordiaUPC", "Courier New", "DaunPenh", "David", "DFKai-SB", "Dialog", "DialogInput", "DilleniaUPC", "DokChampa", "Dotum", "DotumChe", "Ebrima", "Gabriola", "Garamond", "Gautami", "Georgia", "Gisha", "Gulim", "GulimChe", "Gungsuh", "GungsuhChe", "Harrington", "Impact", "Informal Roman", "IrisUPC",
                "Iskoola Pota", "JasmineUPC", "Jokerman", "Juice ITC", "KaiTi", "Kalinga", "Kartika", "Khmer UI", "KodchiangUPC", "Kokila", "Kristen ITC", "Kunstler Script", "Lao UI", "Latha", "Leelawadee", "Levenim MT", "LilyUPC", "Magneto", "Malgun Gothic", "Mangal", "MingLiU", "MingLiU-ExtB", "Miriam Fixed", "Mistral", "Monospaced", "MV Boli", "Narkisim", "NSimSun", "Nyala", "Onyx", "Palatino Linotype", "Parchment", "Playbill", "PMingLiU", "Poor Richard", "Raavi", "Ravie", "Rod", "Sakkal Majalla", "SansSerif", "Segoe Print", "Segoe Script", "Segoe UI", "Segoe UI Light", "Tahoma", "Times New Roman", "Traditional Arabic"};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Estilo de fuente:");

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {"Normal","Cursiva","Negrita"};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel4.setText("Tamaño:");

        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {"8","9","10","11","12","14","16","18","20","22","24","26","28","36","48","72"};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList4);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setEnabled(false);

        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("AaBbYyZz");
        jScrollPane5.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabel5.setText("Muestra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(282, 282, 282))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * Cierra la ventana de formao sin guardar los cambios
     * @param evt Accion del boton
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Aplica los cambios y cierra la ventana
     *
     * @param evt Accion del boton
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.inter.aplicarFormato(font);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

    /**
     * Establece una nueva fuente al texto
     *
     * @param fuente Nueva fuente a establecer
     */
    private void actualizaFuente(String fuente) {
        this.jTextField1.setText(fuente);
        this.font = new Font(fuente, this.font.getStyle(), this.font.getSize());
        this.jTextArea1.setFont(font);
    }

    /**
     * Establece un nuevo estilo al texto
     *
     * @param est Nuevo estilo a esablecer
     */
    private void actualizaEstilo(String est) {
        int estilo;
        if ("Normal".equals(est)) {
            estilo = Font.PLAIN;
        } else {
            if ("Cursiva".equals(est)) {
                estilo = Font.ITALIC;
            } else {
                estilo = Font.BOLD;
            }
        }
        this.jTextField2.setText(est);
        this.font = new Font(this.font.getFontName(), estilo, this.font.getSize());
        this.jTextArea1.setFont(font);
    }

    /**
     * Establece un nuevo tamaño al texto
     *
     * @param tam Nuevo tamaño
     */
    private void actualizaTam(String tam) {
        this.jTextField4.setText(tam);
        this.font = new Font(this.font.getFontName(), this.font.getStyle(), Integer.parseInt(tam));
        this.jTextArea1.setFont(font);
    }

    /**
     * Establece el idioma indicado en la configuracion
     */
    private void setIdiomaInterfaz() {
        this.setTitle(this.config.getPalabra(18));
        jLabel1.setText(this.config.getPalabra(25));
        jLabel2.setText(this.config.getPalabra(26));
        jLabel4.setText(this.config.getPalabra(27));
        jLabel5.setText(this.config.getPalabra(28));
        jButton2.setText(this.config.getPalabra(21));
        jButton1.setText(this.config.getPalabra(22));

        DefaultListModel listModel = new DefaultListModel();
        listModel.addElement(this.config.getPalabra(29));
        listModel.addElement(this.config.getPalabra(30));
        listModel.addElement(this.config.getPalabra(31));
        jList2.setModel(listModel);
    }

    /**
     * Listener para modificar la muestra al seleccionar una nueva fuente
     */
    private static class ListSelectionListenerFuente implements ListSelectionListener {

        private final FormatoFrame f;

        /**
         * Contructor parametrizado del listener
         *
         * @param f Clase frame FormatoFrame
         */
        public ListSelectionListenerFuente(FormatoFrame f) {
            this.f = f;
        }

        /**
         * Modifica la muestra al seleccionar una nueva fuente
         */
        @Override
        public void valueChanged(ListSelectionEvent e) {
            boolean adjust = e.getValueIsAdjusting();
            if (!adjust) {
                JList list = (JList) e.getSource();
                int selections[] = list.getSelectedIndices();
                Object selectionValues[] = list.getSelectedValues();
                for (int i = 0, n = selections.length; i < n; i++) {
                    f.actualizaFuente(selectionValues[i].toString());
                }
            }
        }
    }

    /**
     * Listener para modificar la muestra al seleccionar un nuevo esilo
     */
    private static class ListSelectionListenerEstilo implements ListSelectionListener {

        private final FormatoFrame f;

        /**
         * Contructor parametrizado del listener
         *
         * @param f Clase frame FormatoFrame
         */
        public ListSelectionListenerEstilo(FormatoFrame f) {
            this.f = f;
        }

        /**
         * Modifica la muestra al seleccionar un nuevo esilo
         */
        @Override
        public void valueChanged(ListSelectionEvent e) {
            boolean adjust = e.getValueIsAdjusting();
            if (!adjust) {
                JList list = (JList) e.getSource();
                int selections[] = list.getSelectedIndices();
                Object selectionValues[] = list.getSelectedValues();
                for (int i = 0, n = selections.length; i < n; i++) {
                    f.actualizaEstilo(selectionValues[i].toString());
                }
            }
        }
    }

    /**
     * Listener para modificar la muestra al seleccionar un nuevo tamaño
     */
    private static class ListSelectionListenerTam implements ListSelectionListener {

        private final FormatoFrame f;

        /**
         * Contructor parametrizado del listener
         *
         * @param f Clase frame FormatoFrame
         */
        public ListSelectionListenerTam(FormatoFrame f) {
            this.f = f;
        }

        /**
         * Modifica la muestra al seleccionar un nuevo tamaño
         */
        @Override
        public void valueChanged(ListSelectionEvent e) {
            boolean adjust = e.getValueIsAdjusting();
            if (!adjust) {
                JList list = (JList) e.getSource();
                int selections[] = list.getSelectedIndices();
                Object selectionValues[] = list.getSelectedValues();
                for (int i = 0, n = selections.length; i < n; i++) {
                    f.actualizaTam(selectionValues[i].toString());
                }
            }
        }
    }

}
